### PR TITLE
Create help.rst

### PR DESCRIPTION
**Pull request by aaronw112358**
one page high level for those who find themselves in the situation of "someone told me my ROAs are invalid, but I don't know what that means"

### CODE REVIEW

**Comment by AlexanderBand** [comment]
Thanks a lot for this pull request. I'll have a look in the next few days how to best integrate this into the rest of the content, including TOC and menu structure.

**Comment by aaronw112358** [comment]
Sounds good - it's really an initial stab at a very high level for those people who are not as familiar with the ecosystem.

**Comment by AlexanderBand** [comment]
Now that I'm reading it again, I'm wondering if this format would perhaps work better for the FAQ: https://rpki.readthedocs.io/en/latest/about/faq.html

What do you think?

**Comment by aaronw112358** [comment]
Well, I'm not opposed to it being in there, but what I'm trying to accomplish is having a simple page for organizations that aren't very technical, because as time passes, more large carriers (telia is Oct 4, ATT is already done) will start implementing RPKI and people may not be familiar with it at all.  I'm aiming this page at a small organization/carrier who may have had a person there at a time who had an account on the RIR, set up a ROA for their small number of routes, and since left.   They're not going to run it on their routers, but they got an email from someone saying their ROA is invalid and have no idea what to do next.  Most of the faq page seems aimed a little higher technically and/or seems to be positioned towards people who are going to run it on their own routers, which is fine, but I see this as a gap which needs filled, and this project might be a good place for it.

**Comment by dev-gto** [comment]
Seems to be a troubleshooting page, which is perfect for panic situations (I mean, what to do if anything goes wrong).
I agree that there are several outside sources mentioning technical stuff like RFC's, bringing some complexity for newcomers. A guide for operators, like this one, is very welcome.

**Pull request merged**
