### PR TITLE
add ARIN TAL to FAQ

### PR DESCRIPTION
**Pull request by job**

### CODE REVIEW

**Comment by AlexanderBand** [comment]
Thank you for your pull request. I don't think embedded video is good FAQ material, but I'm more than happy to include a factual, text based entry about this topic and what users should be aware of when venturing into accepting the ARIN TAL.

**Comment by job** [comment]
is it now better?

**Comment by AlexanderBand** [comment]
Thanks for your edits, this is exactly the direction I had in mind. I observe two things:

1. I would prefer to explain *why* the ARIN TAL is problematic in the FAQ itself, instead of requiring the reader to deduct this from an external source
2. I would like to ensure there is a separation between the authors of the documentation and any opinions on the policy

**Comment by job** [comment]
perhaps you can merge and edit as you like?

which sentence is not backed by an external reference? It is not a matter of opinion that prefixes under the ARIN TAL are more susceptible to hijacks due to the TAL situation

**Comment by AlexanderBand** [comment]
How about this?
> Unlike the other RIRs, which distribute their TAL publicly, ARIN has a policy requiring users to explicitly agree to terms and conditions concerning its TAL. Note that this policy is not without controversy (and then refer to discussion)...

**Comment by maelmans** [comment]
Agreed with Alex. I like this wording.

**Pull request merged**
